services:
  ssh-634.cyrhades.fr:
    container_name: ssh-634
    build:
      context: ./.docker/ssh
      args:
        LANGUAGE: ${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
      ho.ctf.cyrhades.webssh: "1"
    environment:
      SSH_HOSTNAME: "ssh-634.cyrhades.fr"
      SSH_PORT: 22
      SSH_USERNAME: "cyrhades"
      SSH_PASSWORD: "secret"
    restart: unless-stopped
  brontosaure.cyrhades.fr:
    image: anssi/fcsc2026-reverse-brontosaure:latest
